### ISSUE TITLE
Taking too long to execute

### ISSUE THREAD

**Issue by SonamChoudhary** [j2kun/fkl-SDM16#5]
Hi,

I was trying to replicate your results. How long does it usually take to run the experiments? I was just executing experiment-SDB.py and it's taking a long time and still not finish. I got just 2 best shift results in two hours. Am I missing any dependencies?

Thanks,
Sonam

**Comment by ben-fish** [comment]
AFAIK, you're not missing any dependences as long as no errors occur.  It takes a while, in part because we repeat experiments to compute standard deviations.  I think we ran experiment-SDB.py overnight to get the full set of results.  @j2kun tells me that he thinks logistic regression might be faster than SVM or boosting, if you just want to try one of them.
-Ben

**Comment by SonamChoudhary** [comment]
Thank you. I'll try that. Also, was there some specific reason for not using svmLearner on the German dataset and for not using svmLinearLearner for adult dataset? Thanks.

**Comment by ben-fish** [comment]
Yes, SVM with a Gaussian kernel performs poorly on the German data set, so we were forced to use a linear kernel instead.  Details in the [paper](http://homepages.math.uic.edu/~bfish3/sdm_2016.pdf).  (The only difference between the two is that svmLearner uses a Gaussian kernel while svmLinearLearner uses a linear kernel.)
